#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > .tmp_file
sudo cp .tmp_file /var/www/html/index.html 
echo "Ceci n'est pas une page" > .tmp_file
sudo cp .tmp_file /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4 ;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
    
}" > .tmp_file
sudo cp .tmp_file /etc/nginx/sites-available/default
rm .tmp_file
sudo service nginx restart
