#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
INDEX_CONT='"Hello World!\n"'
CONT="server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;
    location / {
        add_header X-Served-By $(hostname);
        return 200 $INDEX_CONT;
    }
}"
echo $CONT
echo $CONT > .tmp_file
sudo cp .tmp_file /etc/nginx/sites-available/default
rm .tmp_file
sudo service nginx restart
