#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.5.\*

HNUM="3292"
IP1="34.138.156.219"
IP2="34.74.218.204"
CONT="
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server $HNUM-web-01 $IP1:80 check
    server $HNUM-web-02 $IP2:80 check
"
cp /etc/haproxy/haproxy.cfg .tmp_file
echo $CONT >> .tmp_file
sudo cp .tmp_file /etc/haproxy/haproxy.cfg
sudo rm -r .tmp_file
sudo service haproxy start
