#!/usr/bin/env bash
#Fizz Buzz is in tha house
num=1
while [ "$num" -le 100 ]; do
	flag=0
	if [ $((num % 3)) -eq 0 ]; then
		printf "Fizz"
		((flag = 1))
	fi
	if [ $((num % 5)) -eq 0 ]; then
		printf "Buzz"
		((flag = 1))
	fi
	if [ $flag -eq 0 ]; then
		printf "%d" $num
	fi
	printf "\n"
	((num++))
done
