#!/usr/bin/env bash
# displays Best School 10 times.
VAR=1
while [ "$VAR" -le 10 ]; do
	if [ "$VAR" -eq 4 ]; then
		echo bad luck
	elif [ "$VAR" -eq 8 ]; then
		echo good luck
	else
		echo Best School
	fi
	((VAR += 1))
done
