#!/usr/bin/env bash
# script that configures an Ubuntu server
sed '/127.0.0.1/d' /etc/hosts > ./tmp_file
echo "127.0.0.2 localhost" >> ./tmp_file
echo "8.8.8.8 facebook.com" >> ./tmp_file
cp ./tmp_file /etc/hosts
